### ISSUE TITLE
MSI GTX 1080Ti support?

### ISSUE THREAD

**Issue by ltadi84** [Vipeax/MSI-LED-Tool#31]
As title say will this app support soon Ti models?

**Comment by HologramDK** [comment]
You can edit the Settings.json file to disregard its security check:
"OverwriteSecurityChecks":true

Works with my 1080Ti. I take no responsibility if your card blows up, though :)

**Comment by ltadi84** [comment]
why would anything happend to card like that if this mod is only about LED lights?

**Comment by HologramDK** [comment]
I'd like to start with a big disclaimer and say that I am NOT the developer of this app, so don't hold anything I'm saying against him or her!

The reason I'm saying this is that if you run this application on a 1080Ti, you're running third party software that hasn't been tested by the developer with this specific piece of hardware, or by the manufacturer of the card. I've tested it on my card and I wouldn't have any qualms keeping it running.

However, some people try to blame others for their own actions. Let's say you decided to massively overclock your graphics card and heavily relied on this application to turn the LED's red if temperature suddenly rises. Let's say that this application then crashes, for whatever reason, causing the LEDs to not change color. And then let's say that your graphics card burns out because you weren't aware that it had reached 100 C. 

Some people would instantly come to the conclusion that the developer is to blame for that fuckup. But nobody but yourself is responsible for what happens if you run this tool, and what you use it for. So that is the reason I'm saying the things above. Sorry about the slight scare mongering, but sometimes you just have to cover your ass.

**Comment by rubbingalcoholic** [comment]
FWIW the tool works on my MSI GTX 1080 Ti Gaming X - it's super helpful and saved me from installing MSI's horrible bloatware! Thanks @Vipeax !

**Comment by lpireyn** [comment]
It works with my MSI GTX 1080 Ti if I disable the security checks.

GPU-Z screenshot: http://gpuz.techpowerup.com/17/10/04/ua9.png
